Pr fixs
redhat-beyond/falcon pull request #102
Opened 2021-12-01 23:17 UTC by avraham1992

Fixes #90 #100 #87

## Changes you made

- There is nothing here on the home page
-delete crispy 
- **Please mention someone for code review**
add home and login logout and base templates

2021-12-02 14:18 UTC, aradz1997 approved these changes

2021-12-02 14:57 UTC, natifridman commented
Please give a meaningful name to this PR.
Also, please explain in the description what is this PR for and why you did these changes. For example, why did you delete crispy?

There is no need to close this PR, you can edit it.

2021-12-02 16:22 UTC, Asafh7 submitted a review, later dismissed

2021-12-02 18:05 UTC, natifridman requested changes

2021-12-02 18:05 UTC, natifridman commented on templates/base.html
> +              {% endif %}
As all the users need a logout option, I would write it only once.

```suggestion
            {% if user.is_authenticated %}
              {% if user.Role == Manager %}
                <a class="nav-item nav-link" href="#">New Task</a>
              {% endif %}
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
```

2021-12-02 18:05 UTC, natifridman commented on users/templates/users/logout.html
> +	<h2>you have been log out</h2>
```suggestion
	<h2>you have been logged out</h2>
```

2021-12-03 08:08 UTC, orzionpour approved these changes

2021-12-03 08:38 UTC, AvivLiberman approved these changes

2021-12-03 09:11 UTC, natifridman approved these changes

2021-12-03 09:13 UTC, merged