Fixed urls and redirects
redhat-beyond/falcon pull request #107
Opened 2021-12-04 17:11 UTC by AvivLiberman

Fixes #106 

## Changes you made
- Added app_user to the homepage and not auth_user
- fixed that only Manager sees New Task button
- Moved the navbar to a separate file

2021-12-04 17:21 UTC, avraham1992 reviewed
You intend to create tasks only through the Admin django ?

2021-12-04 17:30 UTC, AvivLiberman commented
@avraham1992 No

2021-12-04 17:30 UTC, orzionpour requested changes
Just to make it a little more readable.

2021-12-04 17:30 UTC, orzionpour commented on templates/base.html
> +    {% include 'navbar.html' %} <div class="container"> {% block content %} {% endblock content %} <div>
```suggestion
    {% include 'navbar.html' %} 
    <div class="container"> 
        {% block content %} {% endblock content %}
    <div>
```

2021-12-04 17:30 UTC, orzionpour commented on templates/homepage.html
>  {% endblock content %}
```suggestion
{% extends "base.html" %} 
{% block content %}
    <h1>HomePage</h1>
{% endblock content %}
```

2021-12-04 17:30 UTC, orzionpour commented on templates/navbar.html
> +        {% endif %}
```suggestion
        {% if user.user.is_authenticated %} 
            {% if user.is_manager %}
                <a class="nav-item nav-link" href="#">New Task</a>
            {% endif %}
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            {% endif %}
```

2021-12-04 17:34 UTC, avraham1992 reviewed
Why is it coming out of the base page (the nav bar) ?

2021-12-04 17:35 UTC, avraham1992 approved these changes

2021-12-04 17:36 UTC, avraham1992 approved these changes

2021-12-04 17:37 UTC, orzionpour submitted a review, later dismissed

2021-12-04 17:46 UTC, avraham1992 submitted a review, later dismissed

2021-12-05 07:16 UTC, natifridman commented
I would also add a redirect from `/login` so if an authenticated user tries this he will be redirected and won't see the login form again.
Also, is there an option to create a redirect from the admin page too? So instead of seeing the default Django error, a regular user won't even be aware that there is an admin page. This is a security concern.

2021-12-05 10:48 UTC, Asafh7 submitted a review, later dismissed

2021-12-05 12:00 UTC, mgold1234 commented
when I logged in with user that is not admin, I don't see the new task button and I suppose to see it. no?
![image](https://user-images.githubusercontent.com/73419853/144745617-c40ed549-45a9-4ec5-9fef-6fd4f73df97e.png)

the Falcon page is only with HomePage' - you need to fix it

2021-12-05 14:48 UTC, avraham1992 commented
> when I logged in with user that is not admin, I don't see the new task button and I suppose to see it. no? ![image](https://user-images.githubusercontent.com/73419853/144745617-c40ed549-45a9-4ec5-9fef-6fd4f73df97e.png)
> 
> the Falcon page is only with HomePage' - you need to fix it

There should be no new task button after exiting only after entering and provided the user's role is manager...The only problem was that we had to give the page to our user so that he could use a role field and not an automatic one that not contains a field of function

2021-12-05 15:30 UTC, aradz1997 submitted a review, later dismissed

2021-12-05 18:16 UTC, AvivLiberman commented
> when I logged in with user that is not admin, I don't see the new task button and I suppose to see it. no? ![image](https://user-images.githubusercontent.com/73419853/144745617-c40ed549-45a9-4ec5-9fef-6fd4f73df97e.png)
> 
> the Falcon page is only with HomePage' - you need to fix it

Only user with Role = Manager will see the New Task button

2021-12-05 18:17 UTC, AvivLiberman commented
> I would also add a redirect from `/login` so if an authenticated user tries this he will be redirected and won't see the login form again. Also, is there any option to create a redirect from the admin page too? So instead of seeing the default Django error, a regular user won't even be aware that there is an admin page. This is a security concern.

Fixed the /login problem, the admin redirect should be in a different PR

2021-12-05 18:38 UTC, orzionpour approved these changes
Looks great :raised_hands: :raised_hands:

2021-12-05 18:57 UTC, Asafh7 approved these changes

2021-12-05 20:55 UTC, mgold1234 commented
please add a meaningful commit message

2021-12-06 08:14 UTC, natifridman approved these changes

2021-12-06 13:04 UTC, kobihk approved these changes

2021-12-06 13:05 UTC, merged