Added view single task page
redhat-beyond/falcon pull request #114
Opened 2021-12-07 18:15 UTC by AvivLiberman

Fixes #95

This PR include view page for single task, for now it is without design.
To make this PR small I have added 2 issues that following it #112, #113
## Changes you made
- Added view_single_task page
- Redirect home if not authenticated
- Path to the page: tasks/<task_id>

2021-12-07 18:20 UTC, orzionpour submitted a review, later dismissed
LGTM  👑

2021-12-07 18:37 UTC, Asafh7 approved these changes

2021-12-08 10:17 UTC, kobihk commented
@AvivLiberman could you please add tests to see that you get the correct response from the client for each page

2021-12-08 20:40 UTC, AvivLiberman commented
> @AvivLiberman could you please add tests to see that you get the correct response from the client for each page
wdym? in the lectures you said we are not testing the UI
@kobihk

2021-12-09 21:01 UTC, AvivLiberman commented
@kobihk Done

2021-12-10 06:31 UTC, avraham1992 submitted a review, later dismissed

2021-12-11 12:44 UTC, orzionpour approved these changes

2021-12-11 20:21 UTC, kobihk requested changes

2021-12-11 20:21 UTC, kobihk commented on tasks/tests/test_view_single_task.py
> +                     password='password')
I don't think you need to break it into a few lines
unless its many variables with a long line for each variable:
```suggestion
        client.login(username=employee_1.user.username, password='password')
```

2021-12-11 20:21 UTC, kobihk commented on tasks/tests/test_view_single_task.py
> +            f'/tasks/{task_1.id}', enforce_csrf_checks=True)
same ^^
```suggestion
        response = client.get(f'/tasks/{task_1.id}', enforce_csrf_checks=True)
```

2021-12-11 20:21 UTC, kobihk commented on tasks/tests/test_view_single_task.py
> +                     password='password')
same ^^
```suggestion
        client.login(username=employee_1.user.username, password='password')
```

2021-12-11 20:21 UTC, kobihk commented on tasks/tests/test_view_single_task.py
> +                     password='password')
same ^^
```suggestion
        client.login(username=employee_1.user.username, password='password')
```

2021-12-12 05:46 UTC, AvivLiberman commented
@kobihk Done

2021-12-12 06:54 UTC, kobihk approved these changes

2021-12-12 06:58 UTC, orzionpour submitted a review, later dismissed

2021-12-12 07:32 UTC, aradz1997 approved these changes

2021-12-12 08:24 UTC, Asafh7 submitted a review, later dismissed

2021-12-12 08:30 UTC, mgold1234 commented
please fix the conflict and then we merge it:)

2021-12-12 12:58 UTC, avraham1992 approved these changes

2021-12-12 16:53 UTC, avraham1992 requested changes
It is not possible to see the tasks if you do not log in to the app so here is a problem according to what I see your bar shows that needs to be done login ..
This means that there is a problem here @AvivLiberman  once there is a separation between landing pages and an external page do not do identification checks again.. it happens because you do not perform identifying that there is no need! The identification is done on the login page and this is it .. what I did is enough you sold not do the identification again insid app Arad have too same he changes it next PR

2021-12-12 17:23 UTC, AvivLiberman commented
> It is not possible to see the tasks if you do not log in to the app so here is a problem according to what I see your bar shows that needs to be done login .. This means that there is a problem here @AvivLiberman once there is a separation between landing pages and an external page do not do identification checks again.. it happens because you do not perform identifying that there is no need! The identification is done on the login page and this is it .. what I did is enough you sold not do the identification again insid app Arad have too same he changes it next PR

Sorry I don't understand the problem

2021-12-12 23:00 UTC, orzionpour approved these changes

2021-12-13 07:44 UTC, avraham1992 approved these changes

2021-12-13 08:09 UTC, natifridman approved these changes

2021-12-13 08:10 UTC, merged