add single task desgin
redhat-beyond/falcon pull request #127
Opened 2021-12-15 20:38 UTC by avraham1992

Fixes #112 (**#115** its close )
## Changes you made

- when it's writing a future option to delete or edit the task
- add single task desgin(by the desgin that @aradz1997 do -\+ )

2021-12-15 21:29 UTC, kobihk commented
> * desgin

2021-12-15 21:31 UTC, kobihk commented
> * add single task desgin(by the desgin that @aradz1997 do -+ )

@avraham1992 please fix the typo: * design in the PR description

2021-12-15 21:36 UTC, kobihk requested changes

2021-12-15 21:36 UTC, kobihk commented on tasks/templates/tasks/view_single_task.html
> +                    {% if  user.is_manager %}
Please remove redundant space
```suggestion
                    {% if user.is_manager %}
```

2021-12-15 21:36 UTC, kobihk commented on tasks/templates/tasks/view_single_task.html
> +                            priority: {{task.priority}}<b>|</b>
Please add spaces to be consistent with the code style in this file
```suggestion
                            priority: {{ task.priority }}<b>|</b>
```

2021-12-15 22:36 UTC, kobihk requested changes

2021-12-15 22:36 UTC, kobihk commented on tasks/templates/tasks/view_single_task.html
> +                     {% if  user.is_manager %}
I meant the redundant space between the "if" to "user.is_manager"
```suggestion
                     {% if user.is_manager %}
```

2021-12-16 06:45 UTC, kobihk approved these changes

2021-12-16 07:06 UTC, natifridman requested changes

2021-12-16 07:06 UTC, natifridman commented on tasks/templates/tasks/view_single_task.html
> +                <div class="media_body">
This div isn't closed

2021-12-16 07:06 UTC, natifridman commented on tasks/templates/tasks/view_single_task.html
> +                </article>
Please fix indentation

2021-12-16 14:22 UTC, natifridman approved these changes

2021-12-16 14:44 UTC, kobihk approved these changes

2021-12-16 14:45 UTC, orzionpour approved these changes

2021-12-17 07:39 UTC, aradz1997 approved these changes

2021-12-17 09:37 UTC, merged