Divide the project to apps
redhat-beyond/falcon pull request #34
Opened 2021-11-11 19:02 UTC by AvivLiberman

#33

2021-11-12 06:20 UTC, avraham1992 reviewed
tanks bro

2021-11-12 12:48 UTC, aradz1997 approved these changes

2021-11-12 13:22 UTC, aradz1997 commented
We need to add the following lines to falcon/setting.py 
INSTALLED_APPS = [
    'Employees.apps.EmployeesConfig',
    'Manager.apps.ManagerConfig',
    'Task.apps.TaskConfig',
]

2021-11-12 13:23 UTC, aradz1997 requested changes
We need to add the following lines to falcon/setting.py
INSTALLED_APPS = [
'Employees.apps.EmployeesConfig',
'Manager.apps.ManagerConfig',
'Task.apps.TaskConfig',
]

2021-11-12 13:58 UTC, avraham1992 requested changes
@AvivLiberman what arad say

2021-11-12 16:36 UTC, orzionpour commented
`# Run database migrations
pipenv run python manage.py migrate`

This line should be added to the `setup.sh` to run the migrations when using `vagrant up`

2021-11-12 16:36 UTC, orzionpour requested changes
`
// Run database migrations //

pipenv run python manage.py migrate
`
This line should be added to the `setup.sh` to run the migrations when using `vagrant up`

2021-11-12 17:05 UTC, AvivLiberman commented
@aradz1997 , @orzionpour Done

2021-11-12 17:06 UTC, orzionpour approved these changes
LGTM

2021-11-12 17:06 UTC, AvivLiberman commented
@mgold1234 @natifridman @nunnatsa can you please CR?

2021-11-12 19:04 UTC, nunnatsa reviewed
I think the data model is good, but I'm not sure about the split between managers an emploees for several reasons. First, the manager is also an emploee. Also, people are moving: team members become managers, moving to other teams or leaving the company. What do you think about removing the managers table, and add a "role" column to the emploee table?

2021-11-13 05:12 UTC, avraham1992 approved these changes

2021-11-13 05:18 UTC, avraham1992 commented on Task/migrations/0001_initial.py
> +                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Manager.manager')),
So you propose to make the manager an employee with permission to write tasks? I only have if it's a problem of the foreign key once a manager leaves must change all the tasks of the employees to the tasks of a new manager...

2021-11-13 06:31 UTC, avraham1992 commented on Task/migrations/0001_initial.py
> +                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Manager.manager')),
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    dob = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

2021-11-13 06:32 UTC, avraham1992 commented on Task/migrations/0001_initial.py
> +                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Manager.manager')),
`from django.db import models
from django.db.models.deletion import CASCADE
from User.models import Profile

class Task(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.RESTRICT)
    title = models.CharField(max_length=50)
    name_task = models.CharField(max_length=50)
    about = models.TextField(blank=True)
    status = models.CharField(max_length=50)
    publish_date = models.DateTimeField()
    property = models.IntegerField()`

2021-11-13 06:32 UTC, avraham1992 commented on Task/migrations/0001_initial.py
> +                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Manager.manager')),
this Okey
?

2021-11-13 06:35 UTC, avraham1992 commented on Task/migrations/0001_initial.py
> +                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Manager.manager')),
Basically I went for the thinking that it's the manager's account so once he leaves he does not have to keep the task board that he no longer deals with pops up...

2021-11-13 07:11 UTC, nunnatsa commented
@AvivLiberman please edit the PR description. Please explain what this PR do, and why is it needed. Description like `#33` won't help the reviewers, and more import, won't help you in the future when tou'll try to remember what was changed in this PR and why it was done, while trying to debug an issue on the customer site, in the middle of the night, on weekend.

2021-11-13 07:15 UTC, mgold1234 commented on Task/migrations/0001_initial.py
> +                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Manager.manager')),
but if the manager will move to a different role in the same company? we want to keep the task board for him

2021-11-13 07:20 UTC, AvivLiberman commented
@nunnatsa it wasn't my PR - I have opened it because @avraham1992 got a mess one

2021-11-13 07:23 UTC, mgold1234 commented
@AvivLiberman, but for someone that open this PR #33 is not clear

2021-11-13 09:13 UTC, AvivLiberman commented
@mgold1234 you are right, I think that this PR include 2 tasks in it:

1.  #25 
2.  #23 

And I don't think the structure is good. I will open new one

2021-11-13 09:13 UTC, closed without merging

2021-11-13 15:34 UTC, mgold1234 commented
@AvivLiberman , why do you think that the structure is not good?