Update the readme file
redhat-beyond/falcon pull request #5
Opened 2021-11-01 19:56 UTC by aradz1997

Updated the readme file
resolve #6

2021-11-01 19:57 UTC, AvivLiberman approved these changes
LGTM

2021-11-01 19:58 UTC, aradz1997 commented
@mgold1234 @nunnatsa @AvivLiberman 
Can you plz review it?

2021-11-01 20:04 UTC, mgold1234 commented on README.md
> +all their tasks in the same place in an organize and easy way, so they will know exactly what to do and when .
when . - delete space before '.'

2021-11-02 04:44 UTC, nunnatsa requested changes
Unfortunately, there are some grammar errors. I would copy the text and paste it in a software like ms word, to find and fix them.

2021-11-02 04:44 UTC, nunnatsa commented on README.md
> +Our product is design to help you control your team work better and easier.
"Our product is" => "Falcon is"

2021-11-02 04:44 UTC, nunnatsa commented on README.md
> +Our product is design to help you control your team work better and easier.
"control" - not sure about this word. Maybe "manage"?

2021-11-02 04:44 UTC, nunnatsa commented on README.md
> +The product allows you as a manager to create new tasks and assigns it to your team, and for your workers, to get
The word "workers" is not in common use these days, I think. Even "employees" is not the best choice. What do you think about "team members"?

2021-11-02 07:23 UTC, AvivLiberman commented
I will go over it again

2021-11-02 07:25 UTC, kobihk requested changes

2021-11-02 07:25 UTC, kobihk commented on README.md
> +![LOGO](https://user-images.githubusercontent.com/62508697/139729943-d46fc1ee-9344-4563-9d7d-2369f38fce54.jpeg)
very nice!!!
maybe it will be better to have this jpeg as part of this repo
IMHO is better to have fewer dependencies in other resources

2021-11-02 07:25 UTC, kobihk commented on README.md
> +| Frontend      | Backennd      | Datebase      |
```suggestion
| Frontend      | Backend      | Datebase      |
```

2021-11-02 07:25 UTC, kobihk commented on README.md
> +![OurTeam](https://user-images.githubusercontent.com/62508697/139729498-30e80549-55f3-41a1-8812-08e92ce03705.jpeg)
same as I explained above about the jpeg...

2021-11-02 07:48 UTC, nunnatsa commented on README.md
>  5. Use any browser and navigate to - `localhost:8000`.
Let's ease our readers by making it a clickable link. 
```suggestion
5. Use any browser and navigate to - [http://localhost:8000](http://localhost:8000).
```

2021-11-02 08:17 UTC, AvivLiberman commented
# Description
**Easy – Fast – Done** :muscle:	

Our product is designed to help you manage your team's tasks and controls workflows in a better, easier way. It has an easy UI for managers and employees with a safe user login.
- Creating new tasks and assign them to your team.
- Overall view of all the tasks with smart filtering system.
- Comments section for discussion on each task.

@aradz1997 Check that out

2021-11-02 08:43 UTC, AvivLiberman commented on README.md
>  # Falcon
# Falcon 🦅

2021-11-02 08:47 UTC, AvivLiberman requested changes

2021-11-02 08:47 UTC, AvivLiberman commented on README.md
>  # Falcon
# Falcon 🦅 
**Easy – Fast – Done** :muscle:	

Our product is designed to help you manage your team's tasks and controls workflows in a better, easier way. It has an easy UI for managers and employees with a safe user login.
- Creating new tasks and assign them to your team.
- Overall view of all the tasks with smart filtering system.
- Comments section for discussion on each task.

@aradz1997 Check that out, I think you can remove the Description title and use only Falcon

2021-11-02 08:49 UTC, AvivLiberman requested changes
@aradz1997 Check that out, I think you can remove the Description title and use only Falcon

2021-11-02 08:49 UTC, AvivLiberman commented on README.md
>  # Falcon
# Falcon 🦅 
**Easy – Fast – Done** :muscle:	

Our product is designed to help you manage your team's tasks and controls workflows in a better, easier way. It has an easy UI for managers and employees with a safe user login.
- Creating new tasks and assign them to your team.
- Overall view of all the tasks with smart filtering system.
- Comments section for discussion on each task.

2021-11-02 11:01 UTC, kobihk commented
@aradz1997 could you please open a new issue related to this PR and add it to the description of this PR
you can see for example:
https://github.com/redhat-beyond/ClassRater/pull/131
fixed:
https://github.com/redhat-beyond/ClassRater/issues/130

2021-11-02 12:19 UTC, AvivLiberman requested changes

2021-11-02 12:31 UTC, nunnatsa commented on README.md
>  # Falcon
But it's an Eagle!

2021-11-02 12:51 UTC, AvivLiberman commented on README.md
>  # Falcon
But there is no Falcon emoji 😞

2021-11-03 13:58 UTC, aradz1997 commented
close #6

2021-11-03 15:40 UTC, aradz1997 commented
fixes #5

2021-11-03 16:03 UTC, kobihk commented
@aradz1997
when you fixed an issue that was raised in the comment it will be better to reply with "Done" or "Fixed" or any other response to make the communication fluent with your code reviewers.

2021-11-03 16:04 UTC, kobihk requested changes

2021-11-05 10:31 UTC, aradz1997 commented on README.md
> +![LOGO](.\Resources\LOGO.jpeg)
DONE

2021-11-05 10:31 UTC, aradz1997 commented on README.md
> +![OurTeam](.\Resources\OurTeam.jpeg)
DONE

2021-11-05 10:33 UTC, aradz1997 commented on README.md
>  3. Open any terminal and navigate to the project directory.
DONE

2021-11-05 10:34 UTC, orzionpour commented
LGTM

2021-11-06 19:56 UTC, kobihk approved these changes

2021-11-06 19:57 UTC, merged