Issue and PR templates
redhat-beyond/falcon pull request #51
Opened 2021-11-14 19:56 UTC by AvivLiberman

added the files into folders so we can add templates in the future

2021-11-15 05:08 UTC, orzionpour approved these changes

2021-11-15 08:11 UTC, natifridman commented
You can also add labels, assignees, etc automatically using a YAML format at the beginning of the file:
```
---
name: Tracking issue
about: Use this template for tracking new features.
title: "[DATE]: [FEATURE NAME]"
labels: tracking issue, needs triage
assignees: octocat
---
```

If you think it's relevant you can add some of this to the templates.

2021-11-15 08:24 UTC, Asafh7 approved these changes

2021-11-15 15:47 UTC, mgold1234 commented
LGTD

2021-11-15 15:56 UTC, kobihk requested changes

2021-11-15 15:56 UTC, kobihk commented on .github/ISSUE_TEMPLATE/bug.md
> +**Please mention somsone to take care of the issue**
```suggestion
**Please mention someone to take care of the issue**
```

2021-11-15 15:56 UTC, kobihk commented on .github/ISSUE_TEMPLATE/feature.md
> +**Please mention somsone to take care of the issue**
```suggestion
**Please mention someone to take care of the issue**
```

2021-11-15 15:56 UTC, kobihk commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +**Please mention somsone for code review**
```suggestion
**Please mention someone for code review**
```

2021-11-16 08:33 UTC, natifridman approved these changes

2021-11-16 12:08 UTC, kobihk approved these changes

2021-11-16 12:08 UTC, merged