Add Tasks Filters
redhat-beyond/falcon pull request #72
Opened 2021-11-23 23:09 UTC by orzionpour

Fixes #62 

## Changes you made

- Add tasks filters
- Add tests for tasks filters

2021-11-24 15:43 UTC, kobihk requested changes

2021-11-24 15:43 UTC, kobihk commented on tasks/models.py
> +    def filterByStatus(cls, status_filter):
the pythonic way is like:
```suggestion
    def filter_by_status(cls, status_filter):
```

2021-11-24 15:43 UTC, kobihk commented on tasks/models.py
> +    def filterByAssignee(cls, assignee_id):
```suggestion
    def filter_by_assignee(cls, assignee_id):
```

2021-11-24 15:43 UTC, kobihk commented on tasks/models.py
> +    def filterByPriority(cls, priority_filter):
```suggestion
    def filter_by_priority(cls, priority_filter):
```

2021-11-24 15:43 UTC, kobihk commented on tasks/test_tasks_filters.py
> +@pytest.mark.django_db()
```suggestion
@pytest.mark.django_db
```

2021-11-24 15:43 UTC, kobihk commented on tasks/test_tasks_filters.py
> +    @pytest.fixture()
```suggestion
    @pytest.fixture
```

2021-11-24 17:44 UTC, Asafh7 submitted a review, later dismissed

2021-11-25 08:20 UTC, kobihk approved these changes

2021-11-25 18:56 UTC, AvivLiberman approved these changes
Just need to merge it correctly with my PR #66

2021-11-26 13:49 UTC, aradz1997 approved these changes

2021-11-26 15:14 UTC, merged